version: '3'

services:
  mrg_php:
    container_name: mrg_php
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www
    networks:
      mrg_network:

  mrg_nginx:
    container_name: mrg_nginx
    build:
      context: ./nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - mrg_php
    networks:
      mrg_network:
    ports:
      - "80:80"
      - "443:443"

  mrg_certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  mrg_postgres:
    container_name: mrg_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
    volumes:
      - mrg_postgres:/var/lib/postgresql/data
    networks:
      mrg_network:
    ports:
      - '127.0.0.1:5432:5432'

#  mrg_redis:
#    container_name: mrg_redis
#    image: redis:6-alpine
#    networks:
#      mrg_network:
#    ports:
#      - "127.0.0.1:6379:6379"

volumes:
  mrg_postgres:

networks:
  mrg_network:
