version: '3'

services:
  mrg_php:
    container_name: mrg_php
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www
    user: ${DOCKER_USER}
    networks:
      mrg_network:

  mrg_nginx:
    container_name: mrg_nginx
    image: nginx:alpine
    command: nginx
    expose:
        - "80"
        - "443"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/backend.conf:/etc/nginx/sites-available/backend.conf
    depends_on:
      - mrg_php
    networks:
      mrg_network:
    ports:
      - "80:80"
      - "443:443"

  mrg_postgres:
    container_name: mrg_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
    volumes:
      - mrg_postgres:/var/lib/postgresql/data
    networks:
      mrg_network:
    ports:
      - '127.0.0.1:5432:5432'

#  mrg_redis:
#    container_name: mrg_redis
#    image: redis:6-alpine
#    networks:
#      mrg_network:
#    ports:
#      - "127.0.0.1:6379:6379"

volumes:
  mrg_postgres:

networks:
  mrg_network:
